apiVersion: platform.encore.com/v1alpha1
kind: EncoreWorkspace
metadata:
  name: maik
  namespace: management
spec:
  team: maik
  responsible: maik.bialas@enercity.de
  alerting: maik.bialas@enercity.de
  costCenter: "12345"
  aadGroupId: 11111-1111-11111-11111
