apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: balbal
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: prod
spec:
  concurrencyPolicy: Forbid
  schedules:
    - 0 * * * *
  timezone: Europe/Berlin
  workflowMetadata:
    labels:
      platform.example.com/environment: prod
  workflowSpec:
    arguments:
      parameters:
        - name: worker-count
          value: "5"
    entrypoint: run-jobs
    templates:
      - name: run-jobs
        parallelism: 2
        steps:
          - - arguments:
                parameters:
                  - name: id
                    value: "{{item}}"
              name: worker
              template: worker
              withSequence:
                count: "{{workflow.parameters.worker-count}}"
                start: "1"
      - container:
          args:
            - |
              echo "Running worker {{inputs.parameters.id}}"
              sleep 30
              echo "Done worker {{inputs.parameters.id}}"
          command:
            - sh
            - -c
          image: alpine:3.20
        inputs:
          parameters:
            - name: id
        name: worker