apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ewer
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: prod
spec:
  schedules:
    - "0 6 * * *"
  timezone: Europe/Berlin
  concurrencyPolicy: Allow
  workflowMetadata:
    labels:
      platform.example.com/environment: prod
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: run
              templateRef:
                name: simple-cluster-workflow-template
                template: main
                clusterScope: true