apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: lucasdemo
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: dev
spec:
  schedules:
    - "0 6 * * *"
  timezone: Europe/Berlin
  concurrencyPolicy: Allow
  workflowMetadata:
    labels:
      platform.example.com/environment: dev
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: run
              templateRef:
                name: basic-image-template
                template: main
                clusterScope: false
              arguments:
                parameters:
                  - name: image
                    value: "registry.example.com/platform-connectors/connector-database:latest"