apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: my-pipeline-2
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: dev
spec:
  schedule: "*/5 * * * *"
  timezone: "UTC"
  concurrencyPolicy: "Replace"

  workflowSpec:
    entrypoint: main
    parallelism: 3   # only 3 pods run in parallel

    templates:
      # Main workflow
      - name: main
        steps:
          # Numbers 1..20
          - - name: process-number
              template: number-workflow
              arguments:
                parameters:
                  - name: number
                    value: "{{item}}"
              withSequence:
                start: "1"
                end: "20"

          # Runs after ALL numbers complete
          - - name: all-done
              template: done

      # Workflow per number
      - name: number-workflow
        inputs:
          parameters:
            - name: number
        steps:
          # Step 1
          - - name: print-number
              template: print

              arguments:
                parameters:
                  - name: number
                    value: "{{inputs.parameters.number}}"

          # Step 2
          - - name: print-step-done
              template: print-step-done

              arguments:
                parameters:
                  - name: number
                    value: "{{inputs.parameters.number}}"

      # Pod: print number
      - name: print
        inputs:
          parameters:
            - name: number

        container:
          image: alpine:3.20
          command: [sh, -c]
          args:
            - |
              echo "{{inputs.parameters.number}}"
              sleep 5

      # Pod: print completion message
      - name: print-step-done
        inputs:
          parameters:
            - name: number

        container:
          image: alpine:3.20
          command: [sh, -c]
          args:
            - |
              echo "step 1 is done for number {{inputs.parameters.number}}"
              sleep 5

      # Final pod
      - name: done
        container:
          image: alpine:3.20
          command: [sh, -c]
          args:
            - |
              echo "DONE"