apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: my-pipeline
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: dev
  annotations:
    cronworkflows.argoproj.io/last-used-schedule: "* * * * *"
spec:
  schedules:
    - "* 10 * * *"
  workflowMetadata:
    labels:
      example: "true"
  workflowSpec:
    arguments:
      parameters:
        - name: message
          value: hello argo
    entrypoint: argosay
    podGC:
      strategy: OnPodCompletion
    templates:
      - container:
          args:
            - echo
            - "{{inputs.parameters.message}}"
          command:
            - /argosay
          image: argoproj/argosay:v2
          name: main
        inputs:
          parameters:
            - name: message
              value: "{{workflow.parameters.message}}"
        name: argosay
    ttlStrategy:
      secondsAfterCompletion: 300