apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: my-pipeline
  namespace: sales-forecasting
  labels:
    platform.example.com/environment: dev
spec:
  workflowMetadata:
    labels:
      example: "true"
  schedules:
    - "* * * * *"
  workflowSpec:
    entrypoint: argosay
    arguments:
      parameters:
        - name: message
          value: hello argo
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: "{{workflow.parameters.message}}"
        container:
          name: main
          image: argoproj/argosay:v2
          command:
            - /argosay
          args:
            - echo
            - "{{inputs.parameters.message}}"
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion