apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: wer
  namespace: sales-forecasting
spec:
  schedule: "0 6 * * *"
  timezone: Europe/Berlin
  concurrencyPolicy: Allow
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: run
              templateRef:
                name: maik
                clusterScope: false
              arguments:
                parameters:
                  - name: target-table
                    value: ""
                  - name: batch-size
                    value: "10000"