apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ttt
  namespace: sales-analytics
  labels:
    platform.example.com/environment: test
  annotations:
    cronworkflows.argoproj.io/last-used-schedule: CRON_TZ=Europe/Berlin 0 6 * * *
spec:
  concurrencyPolicy: Allow
  schedules:
    - 0 6 * * *
  timezone: Europe/Berlin
  workflowMetadata:
    labels:
      platform.example.com/environment: dev
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - arguments:
                parameters:
                  - name: x
                    value: asd
                  - name: y
                    value: asdasdasd2
              name: run
              templateRef:
                clusterScope: false
                name: demo
                template: main