apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: tww
  namespace: sales-analytics
  labels:
    platform.example.com/environment: test
spec:
  concurrencyPolicy: Allow
  schedules:
    - 0 6 * * *
  timezone: Europe/Berlin
  workflowMetadata:
    labels:
      platform.example.com/environment: test
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: run
              templateRef:
                clusterScope: true
                name: simple-cluster-workflow-template
                template: main